# Generated by Django 5.1.2 on 2024-11-02 12:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Необходимо ввести в формате: 7XXXXXXXXXX (X - цифра от 0 до 9)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Неверный формат номер телефона, используйте такой формат: 7XXXXXXXXXX (X - цифра от 0 до 9)', regex='^7\\d{10}$')], verbose_name='Номер телефона клиента')),
                ('mobile_operator_code', models.CharField(help_text='Должен состоять из трех цифр', max_length=3, validators=[django.core.validators.RegexValidator(message='Код мобильного оператора должен состоять из трех цифр', regex='^\\d{3}$')], verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(max_length=50, verbose_name='Тег (произвольная метка)')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время запуска рассылки')),
                ('end_time', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('message_text', models.TextField(verbose_name='Текст сообщения для доставки клиенту')),
                ('mobile_operator_code', models.CharField(max_length=3, verbose_name='Фильтр по коду мобильного оператора клиента')),
                ('tag', models.CharField(max_length=50, verbose_name='Фильтр по тегу клиента')),
                ('task_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID задачи Celery')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('sending_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправки')),
                ('is_sending', models.BooleanField(default=False, verbose_name='Сообщение отправлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
